name: Compile MP4V2
on:
  workflow_dispatch:
  push:
    paths:
      - 'release-versions/*'
      
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [ g++-10 ]
        include:
          - os: ubuntu-latest
            compiler: g++-10
            target: Linux

          - os: macos-latest
            compiler: g++-10
            target: Macos

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Create folders
        run: mkdir mp4v2 && mkdir export
        
      - name: Fetch the mp4v2 Release
        run: RELEASE_VERSION=`cat release-versions/mp4v2-latest.txt` && echo $RELEASE_VERSION && wget https://github.com/enzo1982/mp4v2/releases/download/$RELEASE_VERSION/mp4v2-${RELEASE_VERSION/v}.tar.bz2 && tar -xvjf mp4v2-${RELEASE_VERSION/v}.tar.bz2 -C ./mp4v2
          
      - name: List mp4v2
        run: ls ./mp4v2 && ls ./
        
      - name: Build mp4v2
        run:  RELEASE_VERSION=`cat release-versions/mp4v2-latest.txt` && cd ./mp4v2/mp4v2-${RELEASE_VERSION/v} && ./configure --prefix=../../export && make -j4 && cd make install && make distclean
        
      - uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.os }}
          path: ./export/
