name: Get latest release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/enzo1982/mp4v2/releases/latest | \
          jq -r ".tag_name" > release-versions/mp4v2-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Keenan Nicholson'
          git config --global user.email 'keenanrnicholson@gmail.com'
          git commit -am "New release version"
          git push
